version: '3'
services:
  mslabel-front:
    build:
      context: .
      target: ${BUILD_TARGET}
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
    env_file:
      - .env
    command: sh -c "if [ \"$NODE_ENV\" = \"production\" ]; then node server.js; else npm run dev; fi"